fix #611 for monthly job

diff --git a/jobs/load_monthly b/jobs/load_monthly
--- a/jobs/load_monthly
+++ b/jobs/load_monthly
@@ -14,8 +14,9 @@ jq -c '.[]' bcgw_sources.json | while read item; do
     source=$(jq -r '.source' <<< "$item")
     if [ "$schedule" == "M" ] ; then
       echo "Loading $source from cache"
-      set -e
-      ogr2ogr -f PostgreSQL \
+
+      # this can fail without an exit 1, capture stderr
+      output=$(ogr2ogr -f PostgreSQL \
         "PG:$DATABASE_URL" \
         --config OGR_TRUNCATE=YES \
         -append \
@@ -23,7 +24,12 @@ jq -c '.[]' bcgw_sources.json | while read item; do
         -nln $source \
         --config PG_USE_COPY=YES \
         /vsicurl/https://nrs.objectstore.gov.bc.ca/bchamp/bcdata/$source.parquet \
-        $source || exit 1
+        $source 2>&1)
+
+        if [[ "$output" == *"ERROR"* ]]; then
+          echo "Error detected in command output: $output"
+          exit 1
+        fi
     fi
 done
 
